### PR TITLE
test: add Github action to test PRs

### LINKED ISSUE #793: Set up CI checks in Gatsby repo
Currently while Gatsby has e2e tests, we're not using them to test its own PRs.

Angular has a GitHub workflow set up, Gatsby doesn't. This makes handling Gatsby dependency updates more painful and dangerous for example. Let's add a basic sanity check for Gatsby PRs that runs a build and the tests.

### PR DESCRIPTION
**Pull request by marcelltoth**
Resolves stoplightio/elements#793

### CODE REVIEW

**Comment by marcelltoth** [comment]
It actually caught two linting violations 😄

**Comment by marcelltoth** [comment]
FYI I fixed a flaky test, see my last commit. The fix is not ideal though, the main problem is that the ToC disappears while the redirect is in place from the root URL to the URL of the first item. AFAIK this doesn't (at least didn't use to) happen in regular React. Either a regression or we're using hard browser based navigation here for some reason.

**Review by mmiask — APPROVED** [review]
@marcelltoth I pushed some stuff that will make the tests less flaky. Using `cy.visit()`, even though it works, is not a perfect solution for long term. What I did instead is following:

I used `cy.contains("span", "pets").click();` instead of `cy.get("span").contains("pets").click();` - that makes sure that we query for a specific element on the page and retry if it is not being found. Tests were flaky because somewhere in between `cy.get("span);` and `.contains("pets");` the ToC was detached from DOM - even though at first the `cy.get` was successful, `cy.contains` was not able to search for text within emptiness, once the ToC disappeared.

Using `cy.contains('selector', 'text')` allows you to query (and retry) for a precise element, and each retry happens for that `span` with some text

Other than that, it's good to go! 🎉

**Comment by marcelltoth** [comment]
Awesome, thanks for the fix and the info! 👏

**Pull request merged**
